version: '3.8'

services:
  neo4j:
    image: neo4j:5.12.0
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS='["apoc"]'
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_plugins:starwars_kg_llm/knowledge_graph